export const ActionTypes = {
    SET_WAREHOUSES: "SET_WAREHOUSES",
    SELECTED_WAREHOUSE: "SELECTED_WAREHOUSE",
    REMOVE_SELECTED_WAREHOUSE: "REMOVE_SELECTED_WAREHOUSE",
    SEARCH_WAREHOUSE: "SEARCH_WAREHOUSE",
    SPACE_RANGE_WAREHOUSE: "SPACE_RANGE_WAREHOUSE"
}